apiVersion: v2
name: prometheus-stack
description: A Helm chart for monitoring stack
type: application
version: 0.1.0
appVersion: latest

dependencies:
  - name: kube-prometheus-stack
    version: 82.2.1
    repository: https://prometheus-community.github.io/helm-charts