apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.metadata.name}}
spec:
  selector:
    app: {{.Values.deployment.metadata.name}}
  ports:
    - 
      port: {{.Values.service.port}}
      targetPort: {{.Values.container.port}}
  type: ClusterIP